name: Run Pytest tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pytests:
    runs-on: windows-latest

    steps:
      - name: Checkout main branch repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "${{ github.workspace }}/requirements.txt" ) { pip install -r "${{ github.workspace }}/requirements.txt" }

      - name: Initialize Playwright after
        run: |
          # needed to initialize playwright and download browsers
          python -m playwright install

      - name: Run Pytest and create report
        run: |
          python -m pytest --html=report.html --self-contained-html
        shell: pwsh

      - name: Upload Test Results Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-windows-report
          path: report.html

      - name: Upload XML files created by tests
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: process-outputs
          path: /tests/scrapers/xml/*.xml

      - name: Deploy test results to GH page
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_files: index.html