name: Run Python scrapers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout main branch repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "${{ github.workspace }}/requirements.txt" ) { pip install -r "${{ github.workspace }}/requirements.txt" }

      - name: Run scrapers
        run: |
          foreach ($file in Get-ChildItem -Path "tests/scrapers/*.py" -File) {
          echo "Running file: '$($file.FullName)' "
          python "$($file.FullName)" 
          }